# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Systems Example for Paths
#PATH=$PATH:~cs3214/bin
export PATH

#Display Host
export PS1="\u@\h:[\w] $ " # insert this line and !

#disables noop for for i-search
stty -ixon

source ~/.bashrc

